#
#   Makefile.fpc for FPDoc
#

[package]
name=ifpc
version=2.6.4

[install]
fpcpackage=y

[require]
packages=fcl-process

[target]
programs=ifpc

[compiler]
options=-S2h

[default]
fpcdir=../..

[clean]
units=instantfptools

[rules]
.NOTPARALLEL:
fpdoc$(EXEEXT): instantfpc.pas instantfptools.pas

